server:
  port: 9192

spring:
  datasource:
    url: jdbc:mariadb://database01.c4apmpqoggjv.us-east-2.rds.amazonaws.com:3306/insteadit
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop